set(_CATKIN_CURRENT_PACKAGE "ros_behavior")
set(ros_behavior_VERSION "0.0.0")
set(ros_behavior_MAINTAINER "BioBot <biobotus@gmail.com>")
set(ros_behavior_PACKAGE_FORMAT "1")
set(ros_behavior_BUILD_DEPENDS "roscpp" "rospy" "std_msgs")
set(ros_behavior_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs")
set(ros_behavior_BUILDTOOL_DEPENDS "catkin")
set(ros_behavior_BUILDTOOL_EXPORT_DEPENDS )
set(ros_behavior_EXEC_DEPENDS "roscpp" "rospy" "std_msgs")
set(ros_behavior_RUN_DEPENDS "roscpp" "rospy" "std_msgs")
set(ros_behavior_TEST_DEPENDS )
set(ros_behavior_DOC_DEPENDS )
set(ros_behavior_DEPRECATED "")